site_name: DermAlert
repo_url: https://github.com/DermAlert/dermalert.github.io
repo_name: DermAlert
docs_dir: docs

nav:
  - Home: land/dist/index.html
  - Como Funciona:
    - como-funciona/como-contribuir.md
    - como-funciona/codigo-de-conduta.md
    - como-funciona/guia-de-contribuicao.md
  - Ajuda e Suporte: 
    - ajuda-e-suporte/problemas-comuns.md
    - Documentação técnica:
      - Frontend: ajuda-e-suporte/documentacao-tecnica/frontend.md
      - Backend: ajuda-e-suporte/documentacao-tecnica/backend.md
    - Documentação GCES: 
      - Equipe: ajuda-e-suporte/documentacao-gces/equipe.md
      - Atas de Reunião: ajuda-e-suporte/documentacao-gces/atas-reunioes.md
      - Checklists: ajuda-e-suporte/documentacao-gces/checklist.md
      - Backlog do projeto: ajuda-e-suporte/documentacao-gces/backlog.md
  - Curso de Extensão:
    - curso-de-extensao/sobre-o-curso.md
  - Sobre:
    - sobre/sobre-o-projeto.md
  - Blog:
    - blog/index.md
    
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  language: pt-BR
  favicon: assets/adaptive-icon_black.png
  logo: assets/logo.png
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: "#1A4568" 
      accent: "#1A4568"

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: "#1A4568" 
      accent: "#1A4568"

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  # - exclude:
  #    glob:
  #      - "land/node_modules/**"
  - blog:
      # habilita/desabilita o cálculo automático
      post_readtime: true
      # Número de palavras consideradas por minuto
      post_readtime_words_per_minute: 180

extra_css:
  - assets/stylesheets/extra.css
  - land/dist/assets/index-D5Lwlgl_.css

extra_javascript:
  - land/dist/assets/index-BMjkV8U-.js